---
### Repast Config
#

bind:
  address: 0.0.0.0
  port: 1337

# ssl:
#   cert: ./ssl/repast.crt
#   key: ./ssl/repast.key

backend: http://localhost:4000

filters:
# - headernorm
  - status

# headernorm:
#     add:
#       Accept: application/json
#     require:
#       accept:
#     remove:

# status:
#   message: OK
#   content-type: text/plain

# logging:
#   level: WARN
#   format: '[%(asctime)s] [%(levelname)s] %(message)s'
